spring:
  application:
    name: producer-service
  config:
    import: optional:configserver:http://localhost:8012


eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
server:
  port: 8083